name: A-bank
version: '${version}'
main: org.apo.abank.A_bank
api-version: '1.20'
commands:
  bank:
    description: 은행 기본 명령어
  pay:
    description: 돈 보내기 명령어
  ebank:
    description: 돈 기본 명령어

permissions:
  Bank.*:
    default: op
    description: Give players with op everything by default
  Bank.bank:
    default: false
    description: 은행 기본 명령어 기본 궈한
    children:
      - Bank.bank.list
      - Bank.bank.loan
      - Bank.bank.loanC
      - Bank.bank.loanM
  Bank.pay:
    default: false
    description: 돈 보내기 명령어 기본 권한
  Bank.eco:
    default: false
    description: 돈 기본 명령어 기본 권한
  Bank.ecop:
    default: op

